# Redis Enterprise Database with S3 Backup
#
# This REDB configuration includes automated backups to AWS S3.
#
# Prerequisites:
# - REC deployed
# - S3 bucket created
# - S3 credentials secret created (01-s3-credentials-secret.yaml)
#   OR IRSA configured (for EKS)
#
# Usage:
#   # Update bucket name and region
#   kubectl apply -f 02-redb-s3-backup.yaml
#
# Verification:
#   kubectl get redb test-db -n redis-enterprise
#   kubectl wait --for=condition=Ready redb/test-db -n redis-enterprise --timeout=300s

apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: test-db
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    backup: enabled
spec:
  # Database name
  name: test-db
  
  # Memory size
  memorySize: 1GB
  
  # Database port
  databasePort: 12000
  
  # TLS mode
  tlsMode: enabled
  
  # Replication (high availability)
  replication: true
  
  # Persistence
  persistence: aofEverySecond
  
  # Eviction policy
  evictionPolicy: volatile-lru
  
  # S3 Backup Configuration
  backup:
    # Backup interval in hours (1-24)
    # Backups run every 24 hours
    interval: 24
    
    # Alternative: Backup at specific time (UTC)
    # time: "03:00"  # 3 AM UTC daily
    
    # S3 configuration
    s3:
      # Secret containing AWS credentials
      # Required keys: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
      # Not needed if using IRSA (EKS)
      awsSecretName: s3-backup-credentials
      
      # S3 bucket name
      # ⚠️ REPLACE with your actual bucket name
      bucketName: redis-backups
      
      # Subdirectory within bucket (optional but recommended)
      # Organizes backups by environment/database
      # Example: production/test-db, staging/cache-db
      subdir: production/test-db
      
      # AWS region (optional - auto-detected if not specified)
      # Specify if bucket is in different region than cluster
      # awsRegion: us-east-1

---
# Configuration Explained:
#
# backup.interval:
#   Backup frequency in hours (1-24)
#   Examples:
#     - interval: 1   # Every hour
#     - interval: 6   # Every 6 hours
#     - interval: 12  # Every 12 hours
#     - interval: 24  # Daily
#
# backup.time:
#   Alternative to interval - backup at specific time
#   Format: "HH:MM" (24-hour format, UTC timezone)
#   Examples:
#     - time: "03:00"  # 3 AM UTC
#     - time: "22:00"  # 10 PM UTC
#   
#   ⚠️ Use either interval OR time, not both
#
# s3.awsSecretName:
#   Name of Kubernetes secret containing AWS credentials
#   Required keys:
#     - AWS_ACCESS_KEY_ID
#     - AWS_SECRET_ACCESS_KEY
#   
#   Not needed if using IRSA (IAM Roles for Service Accounts)
#
# s3.bucketName:
#   S3 bucket name (without s3:// prefix)
#   Bucket must exist before creating database
#   
#   Best practices:
#     - Use dedicated bucket for Redis backups
#     - Enable versioning
#     - Enable encryption (SSE-S3 or SSE-KMS)
#     - Block public access
#
# s3.subdir:
#   Subdirectory path within bucket
#   Helps organize backups
#   
#   Recommended structure:
#     - <environment>/<database-name>
#     - <cluster-name>/<database-name>
#     - <region>/<environment>/<database-name>
#   
#   Examples:
#     - production/test-db
#     - staging/cache-db
#     - us-east-1/prod/user-sessions
#
# s3.awsRegion:
#   AWS region where bucket is located
#   Optional - auto-detected from bucket if not specified
#   
#   Specify if:
#     - Bucket is in different region than cluster
#     - Auto-detection fails
#   
#   Examples:
#     - us-east-1
#     - eu-west-1
#     - ap-southeast-1
#
# Backup Retention:
#   Redis Enterprise automatically manages retention:
#     - Last 7 daily backups
#     - Last 4 weekly backups
#     - Last 12 monthly backups
#   
#   Total: Up to 23 backup files per database
#
# Backup File Naming:
#   Format: backup-<timestamp>.rdb
#   Example: backup-2024-01-15-030000.rdb
#
# S3 Path Structure:
#   s3://<bucketName>/<subdir>/backup-<timestamp>.rdb
#   Example: s3://redis-backups/production/test-db/backup-2024-01-15-030000.rdb
#
# Verification:
#   # Check backup configuration
#   kubectl get redb test-db -n redis-enterprise -o yaml | grep -A10 backup
#
#   # List backups in S3
#   aws s3 ls s3://redis-backups/production/test-db/
#
#   # Check backup status via API
#   curl -k -u admin@redis.com:RedisAdmin123! \
#     https://rec.redis-enterprise.svc.cluster.local:9443/v1/bdbs/<bdb-id>/backup

