# RBAC for Redis Enterprise Operator - Multi-Namespace Support
#
# This file configures the necessary permissions for the Redis Enterprise Operator
# to manage resources across multiple namespaces.
#
# Components:
#   1. ClusterRole: Cluster-wide permissions to list namespaces
#   2. ClusterRoleBinding: Binds ClusterRole to operator ServiceAccount
#
# Usage:
#   kubectl apply -f 01-operator-rbac.yaml

---
# ClusterRole for Operator to manage multiple namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-enterprise-operator-consumer-ns
  labels:
    app: redis-enterprise
rules:
  # Permission to list and watch namespaces
  # Required for operator to discover consumer namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]

---
# ClusterRoleBinding to bind ClusterRole to Operator ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-enterprise-operator-consumer-ns
  labels:
    app: redis-enterprise
subjects:
  - kind: ServiceAccount
    name: redis-enterprise-operator
    namespace: redis-enterprise  # Namespace where operator is installed
roleRef:
  kind: ClusterRole
  name: redis-enterprise-operator-consumer-ns
  apiGroup: rbac.authorization.k8s.io

