# RBAC for Consumer Namespaces
#
# This file configures the necessary permissions in consumer namespaces
# for the Operator and REC to manage REDBs.
#
# Components (for EACH consumer namespace):
#   1. Role: Permissions to manage REDBs, secrets, services
#   2. RoleBinding: Binds Role to ServiceAccounts (operator + REC)
#
# Usage:
#   kubectl apply -f 03-consumer-rbac.yaml

---
# Role for app-production namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redb-role
  namespace: app-production
  labels:
    app: redis-enterprise
rules:
  # Permissions to manage REDBs
  - apiGroups: ["app.redislabs.com"]
    resources:
      - redisenterprisedatabases
      - redisenterprisedatabases/status
      - redisenterprisedatabases/finalizers
      - redisenterpriseactiveactivedatabases
      - redisenterpriseactiveactivedatabases/status
      - redisenterpriseactiveactivedatabases/finalizers
    verbs: ["delete", "get", "list", "patch", "create", "update", "watch"]

  # Permissions to manage secrets (credentials)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["update", "get", "watch", "create", "patch", "list"]

  # Permissions to manage services (database endpoints)
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "update", "patch", "create", "delete", "watch"]

  # Permissions to read endpointslices
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

  # Permissions to create events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
# RoleBinding for app-production namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redb-role
  namespace: app-production
  labels:
    app: redis-enterprise
subjects:
  # Operator ServiceAccount
  - kind: ServiceAccount
    name: redis-enterprise-operator
    namespace: redis-enterprise

  # REC ServiceAccount (same name as REC custom resource)
  - kind: ServiceAccount
    name: rec
    namespace: redis-enterprise
roleRef:
  kind: Role
  name: redb-role
  apiGroup: rbac.authorization.k8s.io

---
# Role for app-staging namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redb-role
  namespace: app-staging
  labels:
    app: redis-enterprise
rules:
  - apiGroups: ["app.redislabs.com"]
    resources:
      - redisenterprisedatabases
      - redisenterprisedatabases/status
      - redisenterprisedatabases/finalizers
      - redisenterpriseactiveactivedatabases
      - redisenterpriseactiveactivedatabases/status
      - redisenterpriseactiveactivedatabases/finalizers
    verbs: ["delete", "get", "list", "patch", "create", "update", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["update", "get", "watch", "create", "patch", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "update", "patch", "create", "delete", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
# RoleBinding for app-staging namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redb-role
  namespace: app-staging
  labels:
    app: redis-enterprise
subjects:
  - kind: ServiceAccount
    name: redis-enterprise-operator
    namespace: redis-enterprise
  - kind: ServiceAccount
    name: rec
    namespace: redis-enterprise
roleRef:
  kind: Role
  name: redb-role
  apiGroup: rbac.authorization.k8s.io

---
# Role for app-development namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redb-role
  namespace: app-development
  labels:
    app: redis-enterprise
rules:
  - apiGroups: ["app.redislabs.com"]
    resources:
      - redisenterprisedatabases
      - redisenterprisedatabases/status
      - redisenterprisedatabases/finalizers
      - redisenterpriseactiveactivedatabases
      - redisenterpriseactiveactivedatabases/status
      - redisenterpriseactiveactivedatabases/finalizers
    verbs: ["delete", "get", "list", "patch", "create", "update", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["update", "get", "watch", "create", "patch", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "update", "patch", "create", "delete", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
# RoleBinding for app-development namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redb-role
  namespace: app-development
  labels:
    app: redis-enterprise
subjects:
  - kind: ServiceAccount
    name: redis-enterprise-operator
    namespace: redis-enterprise
  - kind: ServiceAccount
    name: rec
    namespace: redis-enterprise
roleRef:
  kind: Role
  name: redb-role
  apiGroup: rbac.authorization.k8s.io

