# Redis Enterprise Database - Production
#
# REDB criado no namespace app-production, gerenciado pelo REC no namespace redis-enterprise
#
# Características:
#   - Memória: 2GB
#   - Replicação: Habilitada
#   - Persistência: AOF every-1-sec
#   - Eviction: volatile-lru
#   - Porta: 12000
#
# Uso:
#   kubectl apply -f 04-redb-production.yaml
#
# Verificar:
#   kubectl get redb -n app-production
#   kubectl describe redb prod-db-1 -n app-production

---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: prod-db-1
  namespace: app-production  # Consumer namespace
  labels:
    environment: production
    app: redis-database
spec:
  # Nome do REC que gerencia este REDB (no namespace redis-enterprise)
  redisEnterpriseCluster:
    name: redis-enterprise

  # Configurações do database
  memorySize: 2GB
  
  # Replicação habilitada para alta disponibilidade
  replication: true
  
  # Persistência AOF (Append-Only File) a cada 1 segundo
  persistence: aofEveryOneSec
  
  # Política de eviction: remove chaves voláteis menos usadas
  evictionPolicy: volatile-lru
  
  # Porta do database
  databasePort: 12000
  
  # Módulos Redis (todos built-in no Redis Enterprise 8.0)
  modulesList:
    - name: RedisJSON
    - name: RediSearch
    - name: RedisTimeSeries
    - name: RedisBloom
  
  # TLS habilitado para conexões seguras
  tlsMode: enabled
  
  # Backup configuration (opcional)
  # backup:
  #   interval: 24h
  #   s3:
  #     bucketName: redis-backups-prod
  #     subdir: prod-db-1

---
# Secret para credenciais do database (criado automaticamente pelo operator)
# Você pode recuperar as credenciais com:
#   kubectl get secret redb-prod-db-1 -n app-production -o jsonpath='{.data.password}' | base64 -d

