# Redis Enterprise Database - Production
#
# REDB created in app-production namespace, managed by REC in redis-enterprise namespace
#
# Characteristics:
#   - Memory: 2GB
#   - Replication: Enabled
#   - Persistence: AOF every-1-sec
#   - Eviction: volatile-lru
#   - Port: 12001
#
# Usage:
#   kubectl apply -f 04-redb-production.yaml
#
# Verify:
#   kubectl get redb -n app-production
#   kubectl describe redb prod-db -n app-production

---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: prod-db
  namespace: app-production  # Consumer namespace
  labels:
    environment: production
    app: redis-database
spec:
  # Name of REC that manages this REDB (in redis-enterprise namespace)
  redisEnterpriseCluster:
    name: rec

  # Database configuration
  memorySize: 2GB

  # Replication enabled for high availability
  replication: true

  # AOF (Append-Only File) persistence every 1 second
  persistence: aofEverySecond

  # Eviction policy: removes least recently used volatile keys
  evictionPolicy: volatile-lru

  # Database port
  databasePort: 12001

  # TLS enabled for secure connections
  tlsMode: enabled

  # RESP3 protocol support
  resp3: true

  # Use default user
  defaultUser: true

  # Backup configuration (optional)
  # backup:
  #   interval: 24h
  #   s3:
  #     bucketName: redis-backups-prod
  #     subdir: prod-db

---
# Secret for database credentials (created automatically by operator)
# You can retrieve credentials with:
#   kubectl get secret redb-prod-db -n app-production -o jsonpath='{.data.password}' | base64 -d

