# Redis Enterprise Database - Staging
#
# REDB created in app-staging namespace, managed by REC in redis-enterprise namespace
#
# Characteristics:
#   - Memory: 1GB (smaller than production)
#   - Replication: Disabled (to save shards)
#   - Persistence: Snapshot every 6 hours
#   - Eviction: allkeys-lru
#   - Port: 12002
#
# Usage:
#   kubectl apply -f 05-redb-staging.yaml

---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: staging-db
  namespace: app-staging  # Consumer namespace
  labels:
    environment: staging
    app: redis-database
spec:
  redisEnterpriseCluster:
    name: rec

  memorySize: 1GB
  replication: false  # Disabled to save shards (license limit)
  persistence: snapshotEvery6Hour
  evictionPolicy: allkeys-lru
  databasePort: 12002
  tlsMode: enabled
  resp3: true
  defaultUser: true

