# StorageClass for Redis on Flash - GCP Persistent Disk SSD
#
# Este StorageClass usa GCP Persistent Disk SSD para Redis on Flash.
#
# Características:
#   - Provisioner: GCP PD CSI Driver
#   - Type: pd-ssd (SSD Persistent Disk)
#   - Reclaim Policy: Delete
#
# Uso:
#   kubectl apply -f 01-storage-class-gcp.yaml

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-pd-ssd
  labels:
    app: redis-enterprise
    storage-type: flash
provisioner: pd.csi.storage.gke.io
parameters:
  # Type: pd-ssd (SSD Persistent Disk)
  # Outras opções: pd-standard, pd-balanced, pd-extreme
  type: pd-ssd
  
  # Filesystem type
  fsType: ext4
  
  # Replication type: regional-pd para HA
  # Opções: none (zonal), regional-pd (regional)
  replication-type: none

# Reclaim policy: Delete
reclaimPolicy: Delete

# Volume binding mode: WaitForFirstConsumer
volumeBindingMode: WaitForFirstConsumer

# Permite expansão de volumes
allowVolumeExpansion: true

---
# StorageClass alternativo com pd-extreme (para workloads críticos)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-pd-extreme
  labels:
    app: redis-enterprise
    storage-type: flash-premium
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-extreme
  
  # IOPS provisionados (até 120000)
  provisioned-iops-on-create: "100000"
  
  fsType: ext4
  replication-type: none
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# StorageClass para local SSD (máxima performance)
# Requer nodes com local SSD (n2-standard com --local-ssd-count)
# ATENÇÃO: Dados são perdidos se node falhar (use com replicação)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-local-ssd
  labels:
    app: redis-enterprise
    storage-type: flash-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

