# StorageClass for Redis on Flash - AWS EBS gp3
#
# ⚠️ WARNING: EBS volumes (gp3, io2) are NOT recommended for Redis on Flash
# Redis on Flash requires NVMe local SSD for optimal performance
# Use i3, i3en, or i4i instances with local NVMe SSD instead
#
# This StorageClass is provided for reference only
# For production, use local NVMe SSD (see redis-flash-local-ssd below)
#
# Characteristics:
#   - Provisioner: AWS EBS CSI Driver
#   - Type: gp3 (General Purpose SSD v3)
#   - IOPS: 16000 (configurable)
#   - Throughput: 1000 MB/s (configurable)
#   - Reclaim Policy: Delete
#
# Usage:
#   kubectl apply -f 01-storage-class-aws.yaml

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-gp3
  labels:
    app: redis-enterprise
    storage-type: flash
provisioner: ebs.csi.aws.com
parameters:
  type: gp3

  # Provisioned IOPS (3000-16000)
  # Recommended: 16000 for maximum performance
  iops: "16000"

  # Throughput in MB/s (125-1000)
  # Recommended: 1000 for maximum performance
  throughput: "1000"

  # Filesystem type
  fsType: ext4

  # Encryption enabled
  encrypted: "true"

# Reclaim policy: Delete (volumes deleted when PVC is deleted)
reclaimPolicy: Delete

# Volume binding mode: WaitForFirstConsumer
# Ensures volume is created in same AZ as pod
volumeBindingMode: WaitForFirstConsumer

# Allow volume expansion
allowVolumeExpansion: true

---
# Alternative StorageClass with io2 (for critical workloads)
# ⚠️ WARNING: Still not recommended for Redis on Flash - use local NVMe SSD
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-io2
  labels:
    app: redis-enterprise
    storage-type: flash-premium
provisioner: ebs.csi.aws.com
parameters:
  type: io2
  iops: "64000"  # io2 supports up to 64000 IOPS
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# StorageClass for instance store (local SSD - RECOMMENDED for Redis on Flash)
# Requires i3, i3en, i4i nodes with local SSD
# ⚠️ WARNING: Data is lost if node fails (use with replication)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-local-ssd
  labels:
    app: redis-enterprise
    storage-type: flash-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

# To use local SSD, you need to create LocalPersistentVolumes manually
# or use a provisioner like local-volume-provisioner

