# StorageClass for Redis on Flash - GCP Persistent Disk SSD
#
# This StorageClass uses GCP Persistent Disk SSD for Redis on Flash.
#
# Features:
#   - Provisioner: GCP PD CSI Driver
#   - Type: pd-ssd (SSD Persistent Disk)
#   - Reclaim Policy: Delete
#
# Usage:
#   kubectl apply -f 01-storage-class-gcp.yaml

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-pd-ssd
  labels:
    app: redis-enterprise
    storage-type: flash
provisioner: pd.csi.storage.gke.io
parameters:
  # Type: pd-ssd (SSD Persistent Disk)
  # Other options: pd-standard, pd-balanced, pd-extreme
  type: pd-ssd

  # Filesystem type
  fsType: ext4

  # Replication type: regional-pd for HA
  # Options: none (zonal), regional-pd (regional)
  replication-type: none

# Reclaim policy: Delete
reclaimPolicy: Delete

# Volume binding mode: WaitForFirstConsumer
volumeBindingMode: WaitForFirstConsumer

# Allow volume expansion
allowVolumeExpansion: true

---
# Alternative StorageClass with pd-extreme (for critical workloads)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-pd-extreme
  labels:
    app: redis-enterprise
    storage-type: flash-premium
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-extreme

  # Provisioned IOPS (up to 120000)
  provisioned-iops-on-create: "100000"

  fsType: ext4
  replication-type: none
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# StorageClass for local SSD (maximum performance)
# Requires nodes with local SSD (n2-standard with --local-ssd-count)
# WARNING: Data is lost if node fails (use with replication)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-local-ssd
  labels:
    app: redis-enterprise
    storage-type: flash-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

