# StorageClass for Redis on Flash - Azure Premium SSD
#
# This StorageClass uses Azure Premium SSD (managed disks) for Redis on Flash.
#
# Features:
#   - Provisioner: Azure Disk CSI Driver
#   - SKU: Premium_LRS (Premium SSD)
#   - Reclaim Policy: Delete
#
# Usage:
#   kubectl apply -f 01-storage-class-azure.yaml

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-premium-ssd
  labels:
    app: redis-enterprise
    storage-type: flash
provisioner: disk.csi.azure.com
parameters:
  # SKU: Premium_LRS (Premium SSD)
  # Other options: StandardSSD_LRS, UltraSSD_LRS
  skuName: Premium_LRS

  # Filesystem type
  fsType: ext4

  # Caching mode: ReadOnly for better read performance
  cachingMode: ReadOnly

# Reclaim policy: Delete
reclaimPolicy: Delete

# Volume binding mode: WaitForFirstConsumer
volumeBindingMode: WaitForFirstConsumer

# Allow volume expansion
allowVolumeExpansion: true

---
# Alternative StorageClass with Ultra SSD (for critical workloads)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-ultra-ssd
  labels:
    app: redis-enterprise
    storage-type: flash-premium
provisioner: disk.csi.azure.com
parameters:
  skuName: UltraSSD_LRS

  # Provisioned IOPS (up to 160000)
  diskIOPSReadWrite: "64000"

  # Throughput in MB/s (up to 4000)
  diskMBpsReadWrite: "2000"

  fsType: ext4
  cachingMode: None  # Ultra SSD does not support caching
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# StorageClass for local NVMe (Lsv2/Lsv3 series - maximum performance)
# WARNING: Data is lost if node fails (use with replication)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-flash-local-nvme
  labels:
    app: redis-enterprise
    storage-type: flash-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

