# Redis Enterprise Cluster with Redis on Flash
#
# ⚠️ WARNING: This configuration requires NVMe local SSD storage
# NOT recommended for testing on standard EKS with EBS volumes
#
# REC configured to support Redis on Flash with SSD storage.
#
# Characteristics:
#   - 3 nodes
#   - 16GB RAM per node
#   - 500GB Flash/SSD per node
#   - RocksDB storage engine
#   - Replication enabled
#
# Usage:
#   kubectl apply -f 02-rec-with-flash.yaml

---
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: redis-enterprise-flash
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    storage-type: flash
spec:
  # Number of nodes in cluster
  nodes: 3

  # Resources per node
  redisEnterpriseNodeResources:
    limits:
      cpu: "8000m"
      memory: 20Gi  # 16GB for Redis + 4GB for OS
    requests:
      cpu: "4000m"
      memory: 20Gi

  # Redis on Flash configuration
  redisOnFlashSpec:
    # Enable Redis on Flash
    enabled: true

    # Storage engine: rocksdb (recommended) or speedb
    flashStorageEngine: rocksdb

    # Flash/SSD size per node
    # This value defines the PVC size for each pod
    flashDiskSize: 500Gi

  # Persistence configuration for Flash volumes
  persistentSpec:
    enabled: true

    # StorageClass for Flash volumes
    # Choose appropriate for your cloud provider:
    # - redis-flash-gp3 (AWS - NOT recommended, use local NVMe)
    # - redis-flash-premium-ssd (Azure - NOT recommended, use local NVMe)
    # - redis-flash-pd-ssd (GCP - NOT recommended, use local NVMe)
    # - redis-flash-local-ssd (Recommended - local NVMe SSD)
    storageClassName: redis-flash-gp3

    # Volume mode
    volumeMode: Filesystem

  # UI configuration
  uiServiceType: ClusterIP

  # Admin credentials
  username: admin@redis.com

  # License (optional - use trial if no license)
  # licenseSecretName: redis-enterprise-license

  # Services rigger
  servicesRiggerSpec:
    databaseServiceType: ClusterIP
    serviceNaming: bdb_name

  # Rack awareness for HA (optional)
  # rackAwarenessNodeLabel: topology.kubernetes.io/zone

---
# PersistentVolumeClaim template (created automatically by operator)
# This is just an example of what will be created
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-enterprise-flash-0-flash
#   namespace: redis-enterprise
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: redis-flash-gp3
#   resources:
#     requests:
#       storage: 500Gi

