# Redis Enterprise Database with Redis on Flash
#
# ⚠️ WARNING: Requires REC with Redis on Flash enabled
# NOT recommended for testing on standard EKS with EBS volumes
#
# REDB configured to use Redis on Flash with 1:10 ratio (RAM:Flash).
#
# Characteristics:
#   - 10GB RAM (hot data)
#   - 100GB Flash (warm data)
#   - Total capacity: 110GB
#   - Replication enabled
#   - AOF persistence
#
# Usage:
#   kubectl apply -f 03-redb-with-flash.yaml

---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: flash-db
  namespace: redis-enterprise
  labels:
    app: redis-database
    storage-type: flash
spec:
  # Name of REC that manages this REDB
  redisEnterpriseCluster:
    name: redis-enterprise-flash

  # RAM memory for hot data
  memorySize: 10GB

  # Redis on Flash configuration
  redisOnFlashSpec:
    # Enable Redis on Flash for this database
    enabled: true

    # Flash/SSD size for warm data
    # Recommended: 5-10x RAM size
    flashDiskSize: 100GB

  # Replication enabled for high availability
  replication: true

  # AOF (Append-Only File) persistence every 1 second
  persistence: aofEverySecond

  # Eviction policy: volatile-lru
  # Removes least recently used keys with TTL when memory is full
  evictionPolicy: volatile-lru

  # Database port
  databasePort: 12000

  # Redis modules (all built-in in Redis Enterprise 8.0 - no need to specify)
  # modulesList removed - modules are available by default

  # TLS enabled for secure connections
  tlsMode: enabled

  # RESP3 protocol support
  resp3: true

  # Default user enabled
  defaultUser: true

  # Sharding (optional - for very large datasets)
  # shardCount: 3

  # Backup configuration (optional)
  # backup:
  #   interval: 24h
  #   s3:
  #     bucketName: redis-backups
  #     subdir: flash-db

---
# Example 2: Session Store with 1:9 ratio (more Flash)
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: flash-sessions
  namespace: redis-enterprise
  labels:
    app: redis-database
    storage-type: flash
    use-case: session-store
spec:
  redisEnterpriseCluster:
    name: redis-enterprise-flash

  # 5GB RAM for active sessions
  memorySize: 5GB

  redisOnFlashSpec:
    enabled: true
    # 45GB Flash for inactive sessions (1:9 ratio)
    flashDiskSize: 45GB

  replication: true
  persistence: aofEverySecond
  evictionPolicy: volatile-lru
  databasePort: 12001
  tlsMode: enabled
  resp3: true
  defaultUser: true

---
# Example 3: Time-Series with 1:10 ratio (maximum Flash)
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: flash-timeseries
  namespace: redis-enterprise
  labels:
    app: redis-database
    storage-type: flash
    use-case: time-series
spec:
  redisEnterpriseCluster:
    name: redis-enterprise-flash

  # 20GB RAM for recent data
  memorySize: 20GB

  redisOnFlashSpec:
    enabled: true
    # 200GB Flash for historical data (1:10 ratio)
    flashDiskSize: 200GB

  replication: true
  persistence: aofEverySecond
  evictionPolicy: allkeys-lru
  databasePort: 12002

  # Modules removed - all built-in in Redis Enterprise 8.0
  # RedisTimeSeries and RedisJSON available by default

  tlsMode: enabled
  resp3: true
  defaultUser: true

  # Sharding for better performance with large datasets
  shardCount: 3

