kind: RedisEnterpriseCluster
apiVersion: app.redislabs.com/v1
metadata:
  name: rec
  namespace: redis-ns-a
spec:
  nodes: 3
  username: admin@redis.com
  # storageClassName: <your-storageclass>        # optional
  # volumeSize: 20Gi                             # optional     
  persistentSpec:
    enabled: true
  ingressOrRouteSpec:
    apiFqdnUrl: api-rec-redis-ns-a.apps.cluster-lwrtg.dynamic.redhatworkshops.io
    dbFqdnSuffix: -db-rec-redis-ns-a.apps.cluster-lwrtg.dynamic.redhatworkshops.io
    method: openShiftRoute
  bootstrapperImageSpec:
    repository: registry.connect.redhat.com/redislabs/redis-enterprise-operator
  redisEnterpriseServicesRiggerImageSpec:
    repository: registry.connect.redhat.com/redislabs/services-manager
  redisEnterpriseImageSpec:
    repository: registry.connect.redhat.com/redislabs/redis-enterprise
  usageMeter:
    callHomeClient:
      imageSpec:
        repository: registry.connect.redhat.com/redislabs/call-home-client
  redisEnterpriseNodeResources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 2
      memory: 4Gi
