apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-secret-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: db1
      - name: db2
  template:
    metadata:
      name: redis-secret-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/alan-teodoro/poc-argocd
        targetRevision: HEAD
        path: charts/redis-secret
        helm:
          values: |
            secretName: {{name}}-secret
      destination:
        server: https://kubernetes.default.svc
        namespace: redis
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
