---
# SecretStore for Azure Key Vault
#
# Uses Managed Identity for authentication (recommended for AKS).
#
# Prerequisites:
# 1. Azure Key Vault created
# 2. Managed Identity enabled on AKS
# 3. Managed Identity has "Key Vault Secrets User" role
#
# Usage:
#   kubectl apply -f 01-secret-store.yaml

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    component: external-secrets
spec:
  provider:
    azurekv:
      # Azure Key Vault URL
      # Change to your Key Vault name
      vaultUrl: "https://redis-enterprise-kv.vault.azure.net"
      
      # Authentication using Managed Identity (recommended for AKS)
      authType: ManagedIdentity
      
      # Optional: Specify identity client ID
      # If not specified, uses system-assigned managed identity
      # identityId: "<managed-identity-client-id>"

---
# Alternative: Using Service Principal (NOT RECOMMENDED)
#
# Only use for testing. For production, use Managed Identity.
#
# Prerequisites:
# 1. Create Service Principal
# 2. Grant Service Principal access to Key Vault
# 3. Create Kubernetes secret with credentials:
#    kubectl create secret generic azure-credentials \
#      --from-literal=client-id=<CLIENT_ID> \
#      --from-literal=client-secret=<CLIENT_SECRET> \
#      -n redis-enterprise
#
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: azure-key-vault
#   namespace: redis-enterprise
# spec:
#   provider:
#     azurekv:
#       vaultUrl: "https://redis-enterprise-kv.vault.azure.net"
#       authType: ServicePrincipal
#       tenantId: "<TENANT_ID>"
#       authSecretRef:
#         clientId:
#           name: azure-credentials
#           key: client-id
#         clientSecret:
#           name: azure-credentials
#           key: client-secret

---
# Verification:
#   kubectl get secretstore azure-key-vault -n redis-enterprise
#   kubectl describe secretstore azure-key-vault -n redis-enterprise

