---
# ExternalSecret for Redis Database Password (Azure Key Vault)

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-db-password
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    component: database-credentials
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: azure-key-vault
    kind: SecretStore
  
  target:
    name: redis-db-password
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  
  data:
    - secretKey: password
      remoteRef:
        key: redis-database-password  # Azure Key Vault secret name

