---
# Redis Enterprise Cluster using External Secrets (Azure Key Vault)

apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
  namespace: redis-enterprise
spec:
  nodes: 3
  
  redisEnterpriseNodeResources:
    limits:
      cpu: "4"
      memory: 8Gi
    requests:
      cpu: "2"
      memory: 8Gi
  
  persistentSpec:
    enabled: true
    storageClassName: "managed-csi"  # Azure default storage class
    volumeSize: 100Gi
  
  redisEnterpriseImageSpec:
    repository: redislabs/redis
    versionTag: 8.0.6-8
  
  servicesRiggerSpec:
    databaseServiceType: ClusterIP
    serviceNaming: bdb_name
  
  username: admin@redis.com
  credentialsSecret: rec-admin-password  # From ExternalSecret

