# RBAC for Log Collector - All Mode
#
# This RBAC provides full permissions to run the log collector in "all" mode
# (collects ALL resources in the namespace)
#
# ⚠️ WARNING: This RBAC grants broad permissions. Use only when necessary.
#
# Usage:
#   kubectl apply -f 02-rbac-all.yaml
#   kubectl create clusterrolebinding log-collector-all-binding \
#     --clusterrole=redis-log-collector-all \
#     --user=<your-username>

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-log-collector-all
rules:
  # Permissions to read ALL core resources
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - configmaps
      - secrets
      - persistentvolumeclaims
      - persistentvolumes
      - events
      - nodes
      - namespaces
      - serviceaccounts
      - resourcequotas
      - limitranges
    verbs:
      - get
      - list

  # Permissions to read apps resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
      - daemonsets
    verbs:
      - get
      - list

  # Permissions to read batch resources
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list

  # Permissions to read networking resources
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
      - ingressclasses
    verbs:
      - get
      - list

  # Permissions to read storage resources
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
    verbs:
      - get
      - list

  # Permissions to read RBAC resources
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list

  # Permissions to read Redis Enterprise Custom Resources
  - apiGroups: ["app.redislabs.com"]
    resources:
      - redisenterpriseclusters
      - redisenterprisedatabases
      - redisenterpriseremoteclusters
      - redisenterpriseactiveactivedatabases
    verbs:
      - get
      - list

  # Permissions to read policy resources
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
    verbs:
      - get
      - list

  # Permissions to read autoscaling resources
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list

  # Permissions to read admissionregistration resources
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list

  # Permissions to read apiextensions resources (CRDs)
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list

  # Permissions to read cert-manager resources (if installed)
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
    verbs:
      - get
      - list

  # Permissions to read Istio resources (if --collect_istio is used)
  - apiGroups: ["networking.istio.io"]
    resources:
      - virtualservices
      - destinationrules
      - gateways
      - serviceentries
    verbs:
      - get
      - list

  - apiGroups: ["security.istio.io"]
    resources:
      - peerauthentications
      - requestauthentications
      - authorizationpolicies
    verbs:
      - get
      - list

---
# ServiceAccount for log collector (optional)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-log-collector-all
  namespace: redis-enterprise

---
# ClusterRoleBinding for ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-log-collector-all-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-log-collector-all
subjects:
  - kind: ServiceAccount
    name: redis-log-collector-all
    namespace: redis-enterprise

