---
# Redis Enterprise Database with LDAP Authentication (Samba AD)
#
# IMPORTANT: LDAP authentication is configured at the REC level (00-rec-with-ldap.yaml)
# This database uses rolesPermissions to map Redis Enterprise Roles to ACLs
#
# PREREQUISITE: Create Roles and ACLs via Redis Enterprise API or UI first!
#
# Steps to configure LDAP authentication for this database:
# 1. LDAP is already configured in the REC (00-rec-with-ldap.yaml)
# 2. Create Redis Enterprise Roles via API/UI and map them to LDAP groups
# 3. Create Redis Enterprise ACLs via API/UI with the desired permissions
# 4. Use rolesPermissions below to bind Roles to ACLs for this database
#
# For now, this database uses the default user authentication (databaseSecretName)
# To enable LDAP, you must create Roles and ACLs via the Redis Enterprise API or UI
---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-db-ldap
  namespace: redis-enterprise
spec:
  memorySize: 2GB

  # Enable replication for HA
  replication: true

  # Database port
  databasePort: 12000

  # Default user authentication (fallback)
  # The secret will be created automatically with name: redb-redis-db-ldap
  # To disable default user and use LDAP only, set defaultUser: false
  defaultUser: true

  # Redis Enterprise Roles and ACLs binding
  # IMPORTANT: Roles and ACLs must be created via Redis Enterprise API or UI first!
  # Example (commented out - requires Roles/ACLs to be created first):
  # rolesPermissions:
  #   - type: redis-enterprise
  #     role: "redis-admins-role"      # Role name from Redis Enterprise
  #     acl: "admin-acl"                # ACL name from Redis Enterprise
  #   - type: redis-enterprise
  #     role: "redis-developers-role"
  #     acl: "developer-acl"
  #   - type: redis-enterprise
  #     role: "redis-viewers-role"
  #     acl: "viewer-acl"

---
# Deployment and Testing Instructions
---

# ============================================================================
# DEPLOYMENT STEPS
# ============================================================================

# STEP 1: Deploy the database
# kubectl apply -f 01-database-ldap-auth.yaml

# STEP 2: Wait for database to be ready
# kubectl get redb redis-db-ldap -n redis-enterprise -w
# Wait for STATUS: active

# STEP 3: Get the default database password (auto-generated secret)
# kubectl get secret redb-redis-db-ldap -n redis-enterprise -o jsonpath='{.data.password}' | base64 -d
# Save this password for testing

# ============================================================================
# CONFIGURE LDAP AUTHENTICATION (via Redis Enterprise UI or API)
# ============================================================================

# LDAP is already configured at the REC level (00-rec-with-ldap.yaml)
# Now you need to create Roles and ACLs via the Redis Enterprise UI or API

# Option 1: Via Redis Enterprise UI
# 1. Port-forward to UI: kubectl port-forward svc/rec-ui 8443:8443 -n redis-enterprise
# 2. Open browser: https://localhost:8443
# 3. Login with LDAP user (redis-admin / RedisAdmin123!)
# 4. Go to: Access Control > Roles
# 5. Create Roles and map them to LDAP groups:
#    - Role: redis-admins-role → LDAP Group: CN=Redis-Admins,CN=Users,DC=redis,DC=training,DC=local
#    - Role: redis-developers-role → LDAP Group: CN=Redis-Developers,CN=Users,DC=redis,DC=training,DC=local
#    - Role: redis-viewers-role → LDAP Group: CN=Redis-Viewers,CN=Users,DC=redis,DC=training,DC=local
# 6. Go to: Access Control > ACLs
# 7. Create ACLs:
#    - ACL: admin-acl → Rule: allkeys +@all
#    - ACL: developer-acl → Rule: allkeys +@all -@dangerous
#    - ACL: viewer-acl → Rule: allkeys +@read
# 8. Go to: Databases > redis-db-ldap > Configuration > Access Control
# 9. Add Role-ACL bindings:
#    - redis-admins-role → admin-acl
#    - redis-developers-role → developer-acl
#    - redis-viewers-role → viewer-acl

# Option 2: Via Redis Enterprise API (see API documentation)

# ============================================================================
# TESTING
# ============================================================================

# STEP 1: Port-forward to database
# kubectl port-forward svc/redis-db-ldap 12000:12000 -n redis-enterprise

# STEP 2: Test with default user (using password from STEP 3 above)
# redis-cli -h localhost -p 12000 --user default --pass <password-from-secret> PING
# Expected: PONG

# STEP 3: Test with LDAP user redis-admin (after configuring Roles/ACLs)
# redis-cli -h localhost -p 12000 --user redis-admin --pass RedisAdmin123! PING
# Expected: PONG

# STEP 4: Test write with redis-admin
# redis-cli -h localhost -p 12000 --user redis-admin --pass RedisAdmin123! SET test:admin "value"
# Expected: OK

# STEP 5: Test with redis-dev1 (after configuring Roles/ACLs)
# redis-cli -h localhost -p 12000 --user redis-dev1 --pass RedisDev123! SET test:dev "value"
# Expected: OK

# STEP 6: Test dangerous command with redis-dev1 (should fail)
# redis-cli -h localhost -p 12000 --user redis-dev1 --pass RedisDev123! FLUSHALL
# Expected: (error) NOPERM this user has no permissions to run the 'flushall' command

# STEP 7: Test with redis-viewer1 (after configuring Roles/ACLs)
# redis-cli -h localhost -p 12000 --user redis-viewer1 --pass RedisView123! GET test:admin
# Expected: "value"

# STEP 8: Test write with redis-viewer1 (should fail)
# redis-cli -h localhost -p 12000 --user redis-viewer1 --pass RedisView123! SET test:fail "value"
# Expected: (error) NOPERM this user has no permissions to run the 'set' command

