---
# CA ClusterIssuer for cert-manager
#
# This creates a certificate issuer using an existing Certificate Authority (CA).
# Use this when you have your own CA infrastructure.
#
# Use Case: Existing CA infrastructure, enterprise PKI
#
# Prerequisites:
# 1. You have a CA certificate (ca.crt) and private key (ca.key)
# 2. Create a secret with the CA certificate and key:
#
#    kubectl create secret tls ca-key-pair \
#      --cert=ca.crt \
#      --key=ca.key \
#      -n cert-manager
#
# Usage:
#   kubectl apply -f 02b-ca-issuer.yaml
#
# Verify:
#   kubectl get clusterissuer ca-issuer
#   kubectl describe clusterissuer ca-issuer

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  labels:
    app: cert-manager
spec:
  ca:
    secretName: ca-key-pair  # Secret containing CA cert and key in cert-manager namespace

