---
# Proxy Certificate for Redis Enterprise Cluster
#
# This certificate is used for TLS connections to databases.
#
# Used for: Client-to-database TLS connections
# Required: Optional (only if using TLS for databases)
# Auto-renewal: Yes (at 2/3 of lifetime)
#
# IMPORTANT: Must include wildcard or specific database FQDNs in SANs
#
# Prerequisites:
# 1. cert-manager installed
# 2. ClusterIssuer created (e.g., selfsigned-issuer)
#
# Usage:
#   kubectl apply -f 03c-proxy-certificate.yaml
#
# Verify:
#   kubectl get certificate rec-proxy-cert -n redis-enterprise
#   kubectl get secret rec-proxy-cert -n redis-enterprise

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rec-proxy-cert
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    component: proxy-certificate
spec:
  # Secret name where certificate will be stored
  secretName: rec-proxy-cert
  
  # Certificate issuer
  issuerRef:
    name: selfsigned-issuer  # Change to your issuer (ca-issuer, vault-issuer, letsencrypt-prod)
    kind: ClusterIssuer
  
  # Certificate subject
  commonName: "*.redis-enterprise.svc.cluster.local"
  
  # Subject Alternative Names (SANs)
  # IMPORTANT: Include all database FQDNs
  dnsNames:
    - "*.redis-enterprise.svc.cluster.local"  # Internal cluster DNS (wildcard)
    # Add external FQDNs if using ingress:
    # - "*.redis.example.com"  # Wildcard for all databases
    # - redis-db.redis.example.com  # Specific database FQDN
  
  # Certificate validity
  duration: 2160h  # 90 days
  renewBefore: 720h  # Renew 30 days before expiry (at day 60)
  
  # Private key configuration
  privateKey:
    algorithm: RSA
    size: 2048
  
  # Key usages
  usages:
    - digital signature
    - key encipherment
    - server auth

