# ClusterRole and ClusterRoleBinding for Rack Awareness
#
# Required when using rackAwarenessNodeLabel in the REC spec.
# Grants the operator permission to read node labels for zone distribution.
#
# Apply with: kubectl apply -f rbac-rack-awareness.yaml

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-enterprise-operator-nodes-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-enterprise-operator-nodes-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-enterprise-operator-nodes-reader
subjects:
  - kind: ServiceAccount
    name: redis-enterprise-operator
    namespace: redis-enterprise

