# Basic Redis Enterprise Cluster (REC) for EKS
#
# This configuration creates a 3-node Redis Enterprise cluster with:
# - Rack awareness enabled for zone distribution
# - Resource allocation for 2 vCPU / 8Gi memory nodes
# - Persistent storage enabled (required for production)
#
# Prerequisites:
# 1. Redis Enterprise Operator installed
# 2. StorageClass 'redis-storage-gp3' created (storage/gp3-storageclass.yaml)
# 3. Namespace 'redis-enterprise' created
# 4. RBAC for rack awareness applied (rbac-rack-awareness.yaml)
#
# IMPORTANT: Adjust redisEnterpriseNodeResources based on your node size!
# - For 2 vCPU / 8Gi nodes: Use 1 CPU / 4Gi (this config)
# - For 4 vCPU / 16Gi nodes: Use 2 CPU / 8Gi
# - For 8 vCPU / 32Gi nodes: Use 4 CPU / 16Gi
#
# For production deployments, see hardware requirements:
# https://redis.io/docs/latest/operate/rs/installing-upgrading/install/plan-deployment/hardware-requirements/
#
# Apply with: kubectl apply -f rec-basic.yaml

apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
  namespace: redis-enterprise
spec:
  # Number of nodes in the cluster (must be odd number >= 3)
  nodes: 3
  
  # Persistent storage configuration
  persistentSpec:
    enabled: true
    # storageClassName: Uses cluster default StorageClass
    # volumeSize is optional - defaults to 5x memory if omitted (recommended)
    # Uncomment to set explicit size:
    # volumeSize: "100Gi"
  
  # Node resource allocation
  #
  # ⚠️ IMPORTANT: Minimum recommended resources per pod for PRODUCTION:
  # - CPU: 4000m (4 cores)
  # - Memory: 15Gi
  #
  # This configuration uses LOWER resources for TESTING/DEV only.
  # For production deployments, use the recommended minimums above.
  #
  # Testing/Dev resources (current config):
  redisEnterpriseNodeResources:
    limits:
      cpu: "1000m"
      memory: 4Gi
    requests:
      cpu: "1000m"
      memory: 4Gi

  # Production resources (recommended):
  # redisEnterpriseNodeResources:
  #   limits:
  #     cpu: "4000m"      # Minimum 4 cores for production
  #     memory: 16Gi      # Minimum 15Gi for production (16Gi for headroom)
  #   requests:
  #     cpu: "4000m"
  #     memory: 15Gi
  
  # Rack awareness for zone distribution
  # Uses the standard Kubernetes zone label
  # Ensures pods and shards are distributed across availability zones
  #rackAwarenessNodeLabel: topology.kubernetes.io/zone
  
  # Username for the cluster admin
  # Password is stored in the secret 'rec' (01-rec-admin-secret.yaml)
  username: admin@redis.com
  
  # UI service type (ClusterIP for internal access only)
  # Change to LoadBalancer for external access
  #uiServiceType: ClusterIP

  # Services rigger configuration
  # Controls how database services are created
  #servicesRiggerSpec:
    #databaseServiceType: cluster_ip
    #serviceNaming: bdb_name

