# Basic Redis Enterprise Database (REDB) for testing
#
# This configuration creates a simple Redis database with:
# - 1GB memory
# - Replication enabled for high availability
# - AOF persistence (sync every second)
# - No eviction policy (returns errors when memory full)
#
# Connection details will be stored in a Kubernetes secret named "redb-test-db"
#
# Apply with: kubectl apply -f redb-test.yaml

apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: test-db
  namespace: redis-enterprise
spec:
  # Redis database type
  type: redis

  # Enable TLS
  tlsMode: enabled

  # Memory allocation
  memorySize: 1GB

  # Database port (fixed for consistency across environments)
  databasePort: 12000

  # Reference to the Redis Enterprise Cluster
  redisEnterpriseCluster:
    name: rec

  # High availability - creates master and replica
  replication: true

  # Persistence configuration
  # Options: disabled | aofEverySecond | aofAlways | snapshotEvery1Hour | snapshotEvery6Hour | snapshotEvery12Hour
  persistence: aofEverySecond

  # Eviction policy
  # Options: volatile-lru | allkeys-lru | volatile-lfu | allkeys-lfu | volatile-random | allkeys-random | volatile-ttl | noeviction
  # noeviction = return errors when memory limit reached (good for testing)
  evictionPolicy: noeviction

  # Database password from secret
  databaseSecretName: redb-secret

  # Enable RESP3 protocol support
  resp3: true

  # Default user enabled
  defaultUser: true