# Vault CA Certificate Secret
#
# This secret contains the Certificate Authority (CA) certificate used by your Vault server.
# The Redis Enterprise operator uses this to verify the Vault server's TLS certificate.
#
# Prerequisites:
# - Vault server running with TLS
# - Vault CA certificate file available
#
# Instructions:
# 1. Get the Vault CA certificate from your Vault server
# 2. Base64 encode the certificate
# 3. Replace <BASE64_ENCODED_CA_CERT> below with the encoded certificate
#
# OR use kubectl to create the secret directly:
#   kubectl create secret generic vault-ca-cert \
#     --namespace redis-enterprise \
#     --from-file=vault.ca=<path-to-vault-ca.pem>
#
# For self-signed certificates (testing):
#   The vault-ca.pem is the same as vault-cert.pem generated during Vault setup
#
# Verification:
#   kubectl get secret vault-ca-cert -n redis-enterprise
#   kubectl get secret vault-ca-cert -n redis-enterprise -o jsonpath='{.data.vault\.ca}' | base64 -d

apiVersion: v1
kind: Secret
metadata:
  name: vault-ca-cert
  namespace: redis-enterprise
type: Opaque
data:
  # Replace with your base64-encoded Vault CA certificate
  # To encode: cat vault-ca.pem | base64 | tr -d '\n'
  vault.ca: <BASE64_ENCODED_CA_CERT>

---
# Example for reference (DO NOT USE - replace with your actual certificate):
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-ca-cert
#   namespace: redis-enterprise
# type: Opaque
# data:
#   vault.ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lVRXhh...

