kind: Secret
apiVersion: v1
metadata:
  name: rec-b
  namespace: redis-ns-b
  labels:
    app: redis-enterprise
    redis.io/cluster: rec-b
data:
  password: UmVkaXNBZG1pbjEyMyE=
  username: YWRtaW5AcmVkaXMuY29t
type: Opaque