---
# Redis Enterprise Cluster using External Secrets
#
# This REC uses secrets managed by External Secrets Operator.
# The admin password is automatically synced from AWS Secrets Manager.
#
# Prerequisites:
# 1. ExternalSecret created (03-external-secret-admin.yaml)
# 2. Kubernetes secret exists: rec-admin-password
#
# Usage:
#   kubectl apply -f 05-rec-external-secrets.yaml

apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
spec:
  nodes: 3
  
  redisEnterpriseNodeResources:
    limits:
      cpu: "4"
      memory: 8Gi
    requests:
      cpu: "2"
      memory: 8Gi
  
  persistentSpec:
    enabled: true
    storageClassName: "gp3"
    volumeSize: 100Gi
  
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    repository: redislabs/redis
    versionTag: 8.0.6-8
  
  servicesRiggerSpec:
    databaseServiceType: ClusterIP
    serviceNaming: bdb_name
  
  # Admin credentials from External Secrets
  username: admin@redis.com
  credentialsSecret: rec-admin-password  # Created by ExternalSecret

---
# Verification:
#   kubectl get rec rec -n redis-enterprise
#   kubectl describe rec rec -n redis-enterprise
#   kubectl get secret rec -n redis-enterprise -o jsonpath='{.data.password}' | base64 -d

