---
# Redis Enterprise Database using External Secrets
#
# This REDB uses database password managed by External Secrets Operator.
# The password is automatically synced from AWS Secrets Manager.
#
# Prerequisites:
# 1. REC created (05-rec-external-secrets.yaml)
# 2. ExternalSecret created (04-external-secret-database.yaml)
# 3. Kubernetes secret exists: redis-db-password
#
# Usage:
#   kubectl apply -f 06-redb-external-secrets.yaml

apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-db
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    database: redis-db
spec:
  memorySize: 1GB
  replication: true
  persistence: aofEverySecond
  type: redis
  evictionPolicy: volatile-lru
  
  # Database password from External Secrets
  databaseSecretName: redis-db-password  # Created by ExternalSecret
  
  # Optional: Database port
  databasePort: 12000

---
# Verification:
#   kubectl get redb redis-db -n redis-enterprise
#   kubectl describe redb redis-db -n redis-enterprise
#   kubectl get secret redb-redis-db -n redis-enterprise -o jsonpath='{.data.password}' | base64 -d
#
# Test connection:
#   redis-cli -h redis-db.redis-enterprise.svc.cluster.local -p 12000 -a <password> PING

