---
# SecretStore for GCP Secret Manager
#
# Uses Workload Identity for authentication (recommended for GKE).
#
# Prerequisites:
# 1. GCP Secret Manager API enabled
# 2. Workload Identity enabled on GKE
# 3. GCP Service Account created with secretAccessor role
# 4. Kubernetes SA annotated with GCP SA
#
# Usage:
#   kubectl apply -f 01-secret-store.yaml

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    component: external-secrets
spec:
  provider:
    gcpsm:
      # GCP Project ID
      # Change to your GCP project
      projectID: "your-gcp-project"
      
      # Authentication using Workload Identity (recommended for GKE)
      auth:
        workloadIdentity:
          clusterLocation: us-central1  # Change to your cluster region
          clusterName: your-gke-cluster  # Change to your cluster name
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system

---
# Alternative: Using Service Account Key (NOT RECOMMENDED)
#
# Only use for testing. For production, use Workload Identity.
#
# Prerequisites:
# 1. Create GCP Service Account
# 2. Grant Service Account secretAccessor role
# 3. Create and download service account key JSON
# 4. Create Kubernetes secret:
#    kubectl create secret generic gcp-credentials \
#      --from-file=credentials.json=./service-account-key.json \
#      -n redis-enterprise
#
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: gcp-secret-manager
#   namespace: redis-enterprise
# spec:
#   provider:
#     gcpsm:
#       projectID: "your-gcp-project"
#       auth:
#         secretRef:
#           secretAccessKeySecretRef:
#             name: gcp-credentials
#             key: credentials.json

---
# Verification:
#   kubectl get secretstore gcp-secret-manager -n redis-enterprise
#   kubectl describe secretstore gcp-secret-manager -n redis-enterprise

