---
# Redis Enterprise Database using External Secrets (GCP Secret Manager)

apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-db
  namespace: redis-enterprise
spec:
  memorySize: 1GB
  replication: true
  persistence: aofEverySecond
  type: redis
  evictionPolicy: volatile-lru
  databaseSecretName: redis-db-password  # From ExternalSecret
  databasePort: 12000

