apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec-a
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
spec:
  nodes: 3
  username: admin@redis.com
  
  # Ingress configuration with nip.io DNS
  # Ingress Controller IP: 34.134.82.175
  ingressOrRouteSpec:
    apiFqdnUrl: rec-a-api.34.134.82.175.nip.io
    dbFqdnSuffix: .db-rec-a.34.134.82.175.nip.io
    method: ingress
    ingressAnnotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

  # UI Service (optional LoadBalancer for direct access)
  uiServiceType: LoadBalancer
  
  persistentSpec:
    enabled: true
    volumeSize: 10Gi
    # storageClassName: gp3  # Uncomment and set for your platform
  
  redisEnterpriseNodeResources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 2
      memory: 4Gi
  
  # Rack awareness disabled (nodes don't have zone labels)
  # rackAwarenessNodeLabel: topology.kubernetes.io/zone

