apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseActiveActiveDatabase
metadata:
  name: aadb
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
spec:
  globalConfigurations:
    # Database memory (total across all participating clusters)
    memorySize: 200MB
    
    # Number of shards
    shardCount: 1
    
    # Database port (fixed for consistency)
    databasePort: 12000
    
    # Database password from secret
    databaseSecretName: reaadb-secret
    
    # Disable replication for testing (requires more nodes for rack awareness)
    replication: false
    
    # TLS mode (enabled, disabled, replica_ssl)
    tlsMode: enabled
    
    # Optional: Redis modules (must support CRDT)
    # modulesList:
    #   - name: rejson
    #     version: 2.8.10
  
  # Participating clusters (both clusters must be defined)
  participatingClusters:
    - name: rerc-a
    - name: rerc-b

