# Optimized gp3 StorageClass for EKS (Default)
#
# gp3 is the recommended storage type for AWS EKS workloads:
# - Better performance than gp2 at lower cost
# - Baseline 3,000 IOPS and 125 MB/s throughput (configurable)
# - Volume expansion supported
# - Encryption enabled by default
# - WaitForFirstConsumer binding mode (ensures volume created in same AZ as pod)
#
# This StorageClass is configured as the cluster default.
#
# To apply:
# 1. Remove gp2 as default: kubectl patch storageclass gp2 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
# 2. Apply this file: kubectl apply -f gp3-storageclass.yaml
#
# Reference: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"              # Baseline IOPS (can increase up to 16,000)
  throughput: "125"         # Baseline throughput in MB/s (can increase up to 1,000)
  encrypted: "true"         # Enable encryption at rest
  # fsType: ext4            # Default filesystem (ext4 is default)
volumeBindingMode: WaitForFirstConsumer  # Ensures volume is created in same AZ as pod
allowVolumeExpansion: true                # Allow PVC expansion
reclaimPolicy: Delete                     # Delete volume when PVC is deleted

